all:	configure

configure:	 Makefile.in configure.ac
	@autoheader
	@autoconf
	@rm -rf *.cache

clean:
	@if [ -f Makefile ]; then make clean; fi || true
	@rm -rvf Makefile configure config.* .ui .obj .moc
	@rm -rvf *.cache *.log *.status *.pro *.spec *.desktop
