all:	configure

configure:	 Makefile.in configure.ac
	@autoheader
	@autoconf
	@rm -rf *.cache

clean:
	@if [ -f Makefile ]; then make clean; fi || true
	@rm -rvf Makefile configure config.* src/.ui src/.obj src/.moc
	@rm -rvf src/Makefile src/config.* src/*.pri src/*.desktop
	@rm -rvf *.cache *.log *.status *.spec
