.TH QTRACTOR 1 "June 17, 2014"
.SH NAME
Qtractor \- An Audio/MIDI multi\-track sequencer
.SH SYNOPSIS
.B qtractor
[\fIoptions\fR] [\fIsession-file\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B qtractor
command.
.PP
\fBQtractor\fP is an audio/MIDI multi-track sequencer application
written in C++ with the Qt framework. Target platform is Linux,
where the Jack Audio Connection Kit (JACK) for audio and the
Advanced Linux Sound Architecture (ALSA) for MIDI are the main
infrastructures to evolve as a fairly-featured Linux desktop audio
workstation GUI, specially dedicated to the personal home-studio.
.SH OPTIONS
.HP
\fB\-s, \fB\-\-session-id\fR=[\fIuuid\fR]
.IP
Set session identification (uuid)
.HP
\fB\-?, \fB\-\-help\fR
.IP
Show help about command line options
.HP
\fB\-v, \fB\-\-version\fR
.IP
Show version information
.SH FILES
Configuration settings are stored in ~/.config/rncbc.org/Qtractor.conf
.SH AUTHOR
Qtractor was written by Rui Nuno Capela.
.PP
This manual page was written by Gürkan Sengün <gurkan@phys.ethz.ch>,
for the Debian project (but may be used by others).
